package fr.the__glacier.gcore.util;

import de.tr7zw.changeme.nbtapi.NBT;
import de.tr7zw.changeme.nbtapi.iface.ReadWriteNBT;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class ItemStackUtil {

    public ItemStack setSkullOwner(ItemStack it, UUID puuid){
        if (it.getType() != Material.PLAYER_HEAD) throw new Error("Trying to set a skull texture to a non player head item.");
        NBT.modify(it, nbt -> {
            ReadWriteNBT skullOwnerCompound = nbt.getOrCreateCompound("SkullOwner");
            skullOwnerCompound.setUUID("Id", puuid);
        });
        return it;
    }
    public ItemStack setSkullTexture(ItemStack it, String texture){
        if (it.getType() != Material.PLAYER_HEAD) throw new Error("Trying to set a skull texture to a non player head item.");
        NBT.modify(it, nbt -> {
            ReadWriteNBT skullOwnerCompound = nbt.getOrCreateCompound("SkullOwner");
            skullOwnerCompound.setUUID("Id", UUID.randomUUID());
            skullOwnerCompound.getOrCreateCompound("Properties").getCompoundList("texture").addCompound().setString("Value", texture);
        });
        return it;
    }
    public static List<SortType> getSortType(ItemStack itemStack){
        List<SortType> list = new ArrayList<>(getSortType(itemStack.getType()));
        if (itemStack.getType().isBlock()){
            list.add(SortType.BLOCK);
        }
        return list;
    }
    public static List<SortType> getSortType(Material type){
        return switch (type) {
            case ACACIA_BOAT, ACACIA_DOOR, ACACIA_CHEST_BOAT, ACACIA_FENCE, ACACIA_FENCE_GATE, ACACIA_LOG, ACACIA_PLANKS, ACACIA_HANGING_SIGN, ACACIA_SIGN, ACACIA_SLAB, ACACIA_STAIRS, ACACIA_TRAPDOOR, ACACIA_WOOD, STRIPPED_ACACIA_LOG, STRIPPED_ACACIA_WOOD, OAK_BOAT, OAK_DOOR, OAK_CHEST_BOAT, OAK_FENCE, OAK_FENCE_GATE, OAK_LOG, OAK_PLANKS, OAK_HANGING_SIGN, OAK_SIGN, OAK_SLAB, OAK_STAIRS, OAK_TRAPDOOR, OAK_WOOD, STRIPPED_OAK_LOG, STRIPPED_OAK_WOOD, BIRCH_BOAT, BIRCH_DOOR, BIRCH_BUTTON, BIRCH_CHEST_BOAT, BIRCH_FENCE, BIRCH_FENCE_GATE, BIRCH_LOG, BIRCH_PLANKS, BIRCH_HANGING_SIGN, BIRCH_SIGN, BIRCH_SLAB, BIRCH_STAIRS, BIRCH_TRAPDOOR, BIRCH_WOOD, STRIPPED_BIRCH_LOG, STRIPPED_BIRCH_WOOD, SPRUCE_BOAT, SPRUCE_DOOR, SPRUCE_CHEST_BOAT, SPRUCE_FENCE, SPRUCE_FENCE_GATE, SPRUCE_LOG, SPRUCE_PLANKS, SPRUCE_HANGING_SIGN, SPRUCE_SIGN, SPRUCE_SLAB, SPRUCE_STAIRS, SPRUCE_TRAPDOOR, SPRUCE_WOOD, STRIPPED_SPRUCE_LOG, STRIPPED_SPRUCE_WOOD, JUNGLE_BOAT, JUNGLE_DOOR, JUNGLE_CHEST_BOAT, JUNGLE_FENCE, JUNGLE_FENCE_GATE, JUNGLE_LOG, JUNGLE_PLANKS, JUNGLE_HANGING_SIGN, JUNGLE_SIGN, JUNGLE_SLAB, JUNGLE_STAIRS, JUNGLE_TRAPDOOR, JUNGLE_WOOD, STRIPPED_JUNGLE_WOOD, STRIPPED_JUNGLE_LOG, DARK_OAK_BOAT, DARK_OAK_DOOR, DARK_OAK_CHEST_BOAT, DARK_OAK_FENCE, DARK_OAK_FENCE_GATE, DARK_OAK_LOG, DARK_OAK_PLANKS, DARK_OAK_HANGING_SIGN, DARK_OAK_SIGN, DARK_OAK_SLAB, DARK_OAK_STAIRS, DARK_OAK_TRAPDOOR, DARK_OAK_WOOD, STRIPPED_DARK_OAK_WOOD, STRIPPED_DARK_OAK_LOG, CHERRY_BOAT, CHERRY_DOOR, CHERRY_CHEST_BOAT, CHERRY_FENCE, CHERRY_FENCE_GATE, CHERRY_LOG, CHERRY_PLANKS, CHERRY_HANGING_SIGN, CHERRY_SIGN, CHERRY_SLAB, CHERRY_STAIRS, CHERRY_TRAPDOOR, CHERRY_WOOD, STRIPPED_CHERRY_WOOD, STRIPPED_CHERRY_LOG, MANGROVE_BOAT, MANGROVE_DOOR, MANGROVE_CHEST_BOAT, MANGROVE_FENCE, MANGROVE_FENCE_GATE, MANGROVE_LOG, MANGROVE_PLANKS, MANGROVE_HANGING_SIGN, MANGROVE_SIGN, MANGROVE_SLAB, MANGROVE_STAIRS, MANGROVE_TRAPDOOR, MANGROVE_WOOD, STRIPPED_MANGROVE_WOOD, STRIPPED_MANGROVE_LOG, BAMBOO_RAFT, BAMBOO_DOOR, BAMBOO_CHEST_RAFT, BAMBOO_FENCE, BAMBOO_FENCE_GATE, BAMBOO_PLANKS, BAMBOO_HANGING_SIGN, BAMBOO_SIGN, BAMBOO_SLAB, BAMBOO_STAIRS, BAMBOO_TRAPDOOR, BAMBOO_BLOCK, STRIPPED_BAMBOO_BLOCK, BAMBOO_MOSAIC_SLAB, BAMBOO_MOSAIC_STAIRS, BAMBOO_MOSAIC ->
                    List.of(SortType.WOOD);
            case MANGROVE_PRESSURE_PLATE, MANGROVE_BUTTON, CHERRY_PRESSURE_PLATE, CHERRY_BUTTON, DARK_OAK_PRESSURE_PLATE, DARK_OAK_BUTTON, JUNGLE_PRESSURE_PLATE, JUNGLE_BUTTON, SPRUCE_PRESSURE_PLATE, SPRUCE_BUTTON, BIRCH_PRESSURE_PLATE, OAK_PRESSURE_PLATE, OAK_BUTTON, ACACIA_PRESSURE_PLATE, ACACIA_BUTTON, BAMBOO_PRESSURE_PLATE, BAMBOO_BUTTON ->
                    List.of(SortType.REDSTONE, SortType.WOOD);
            case ACACIA_SAPLING, ACACIA_LEAVES, OAK_SAPLING, OAK_LEAVES, BIRCH_SAPLING, BIRCH_LEAVES, SPRUCE_SAPLING, SPRUCE_LEAVES, JUNGLE_SAPLING, JUNGLE_LEAVES, DARK_OAK_SAPLING, DARK_OAK_LEAVES, CHERRY_SAPLING, CHERRY_LEAVES, MANGROVE_PROPAGULE, MANGROVE_LEAVES, MANGROVE_ROOTS, MUDDY_MANGROVE_ROOTS, AZALEA_LEAVES, FLOWERING_AZALEA_LEAVES ->
                    List.of(SortType.WOOD, SortType.NATURAL_BLOCK);
            case CRIMSON_DOOR, CRIMSON_FENCE, CRIMSON_FENCE_GATE, CRIMSON_STEM, CRIMSON_PLANKS, CRIMSON_HANGING_SIGN, CRIMSON_SIGN, CRIMSON_SLAB, CRIMSON_STAIRS, CRIMSON_TRAPDOOR, CRIMSON_HYPHAE, STRIPPED_CRIMSON_HYPHAE, STRIPPED_CRIMSON_STEM, WARPED_DOOR, WARPED_FENCE, WARPED_FENCE_GATE, WARPED_STEM, WARPED_PLANKS, WARPED_HANGING_SIGN, WARPED_SIGN, WARPED_SLAB, WARPED_STAIRS, WARPED_TRAPDOOR, WARPED_HYPHAE, STRIPPED_WARPED_HYPHAE, STRIPPED_WARPED_STEM ->
                    List.of(SortType.NETHER, SortType.WOOD);
            case WARPED_PRESSURE_PLATE, WARPED_BUTTON, CRIMSON_PRESSURE_PLATE, CRIMSON_BUTTON ->
                    List.of(SortType.NETHER, SortType.WOOD, SortType.REDSTONE);
            case WARPED_FUNGUS, WARPED_NYLIUM, WARPED_ROOTS, WARPED_WART_BLOCK, TWISTING_VINES, CRIMSON_FUNGUS, CRIMSON_NYLIUM, CRIMSON_ROOTS, WEEPING_VINES, NETHER_SPROUTS, NETHERRACK, NETHER_BRICK, NETHER_BRICK_FENCE, NETHER_BRICK_SLAB, NETHER_BRICK_STAIRS, NETHER_BRICK_WALL, NETHER_BRICKS, CHISELED_NETHER_BRICKS, CRACKED_NETHER_BRICKS, BLACKSTONE, BLACKSTONE_SLAB, BLACKSTONE_STAIRS, BLACKSTONE_WALL, GILDED_BLACKSTONE, POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_BRICK_SLAB, POLISHED_BLACKSTONE_BRICK_STAIRS, POLISHED_BLACKSTONE_BRICK_WALL, POLISHED_BLACKSTONE_BRICKS, CRACKED_POLISHED_BLACKSTONE_BRICKS, POLISHED_BLACKSTONE_SLAB, POLISHED_BLACKSTONE_STAIRS, POLISHED_BLACKSTONE_WALL, CHISELED_POLISHED_BLACKSTONE, BASALT, POLISHED_BASALT, SMOOTH_BASALT, RED_NETHER_BRICK_SLAB, RED_NETHER_BRICK_STAIRS, RED_NETHER_BRICK_WALL, RED_NETHER_BRICKS, NETHER_WART_BLOCK, SOUL_SAND, SOUL_SOIL, MAGMA_BLOCK, OBSIDIAN, CRYING_OBSIDIAN, NETHER_GOLD_ORE, SHROOMLIGHT ->
                    List.of(SortType.NETHER);
            case NETHER_WART -> List.of(SortType.NETHER, SortType.CROP);
            case POLISHED_BLACKSTONE_PRESSURE_PLATE, POLISHED_BLACKSTONE_BUTTON ->
                    List.of(SortType.NETHER, SortType.REDSTONE);
            case ANCIENT_DEBRIS, NETHERITE_BLOCK, NETHERITE_INGOT, NETHER_QUARTZ_ORE, QUARTZ, NETHERITE_SCRAP ->
                    List.of(SortType.NETHER, SortType.MINERAI);
            case TARGET, LEVER, DAYLIGHT_DETECTOR, SCULK_SENSOR, CALIBRATED_SCULK_SENSOR, TRIPWIRE_HOOK, TNT, REDSTONE_LAMP, NOTE_BLOCK, STONE_BUTTON, STONE_PRESSURE_PLATE, LIGHT_WEIGHTED_PRESSURE_PLATE, HEAVY_WEIGHTED_PRESSURE_PLATE, IRON_DOOR, IRON_TRAPDOOR, POWERED_RAIL, DETECTOR_RAIL, RAIL, ACTIVATOR_RAIL ->
                    List.of(SortType.REDSTONE);
            case COAL, COAL_BLOCK, COAL_ORE, IRON_ORE, IRON_INGOT, IRON_BLOCK, IRON_NUGGET, RAW_IRON, RAW_IRON_BLOCK, COPPER_BLOCK, COPPER_INGOT, COPPER_ORE, RAW_COPPER, RAW_COPPER_BLOCK, GOLD_BLOCK, GOLD_INGOT, GOLD_NUGGET, GOLD_ORE, RAW_GOLD, RAW_GOLD_BLOCK, REDSTONE_ORE, LAPIS_BLOCK, LAPIS_LAZULI, LAPIS_ORE, DIAMOND, DIAMOND_ORE, DIAMOND_BLOCK, EMERALD, EMERALD_BLOCK, EMERALD_ORE, DEEPSLATE_COAL_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_GOLD_ORE, DEEPSLATE_REDSTONE_ORE, DEEPSLATE_EMERALD_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_DIAMOND_ORE, AMETHYST_BLOCK, AMETHYST_SHARD ->
                    List.of(SortType.MINERAI);
            case REDSTONE, REDSTONE_BLOCK -> List.of(SortType.MINERAI, SortType.REDSTONE);
            case SHORT_GRASS, FERN, AZALEA, FLOWERING_AZALEA, DEAD_BUSH, SEAGRASS, SEA_PICKLE, DANDELION, POPPY, BLUE_ORCHID, ALLIUM, AZURE_BLUET, RED_TULIP, ORANGE_TULIP, WHITE_TULIP, PINK_TULIP, OXEYE_DAISY, CORNFLOWER, LILY_OF_THE_VALLEY, WITHER_ROSE, TORCHFLOWER, PITCHER_PLANT, SPORE_BLOSSOM, BROWN_MUSHROOM, RED_MUSHROOM, MOSS_CARPET, PINK_PETALS, MOSS_BLOCK, HANGING_ROOTS, BIG_DRIPLEAF, SMALL_DRIPLEAF, CHORUS_PLANT, CHORUS_FLOWER, CARVED_PUMPKIN, JACK_O_LANTERN, BROWN_MUSHROOM_BLOCK, RED_MUSHROOM_BLOCK, MUSHROOM_STEM, VINE, GLOW_LICHEN, MYCELIUM, LILY_PAD, HAY_BLOCK, SUNFLOWER, LILAC, ROSE_BUSH, PEONY, TALL_GRASS, LARGE_FERN, GRASS_BLOCK, DIRT, COARSE_DIRT, PODZOL, ROOTED_DIRT, APPLE, POISONOUS_POTATO, GLISTERING_MELON_SLICE, POPPED_CHORUS_FRUIT ->
                    List.of(SortType.NATURAL_BLOCK);
            case WHEAT_SEEDS, WHEAT, BREAD, SUGAR_CANE, KELP, BAMBOO, CACTUS, PUMPKIN, MELON, COCOA_BEANS, MELON_SLICE, PUMPKIN_SEEDS, MELON_SEEDS, CARROT, POTATO, CHORUS_FRUIT, TORCHFLOWER_SEEDS, PITCHER_POD, BEETROOT, BEETROOT_SEEDS, SWEET_BERRIES, GLOW_BERRIES ->
                    List.of(SortType.NATURAL_BLOCK, SortType.CROP);
            case SPAWNER, TURTLE_EGG, SNIFFER_EGG, ALLAY_SPAWN_EGG, AXOLOTL_SPAWN_EGG, BAT_SPAWN_EGG, BEE_SPAWN_EGG, BLAZE_SPAWN_EGG, CAT_SPAWN_EGG, CAMEL_SPAWN_EGG, CAVE_SPIDER_SPAWN_EGG, CHICKEN_SPAWN_EGG, COD_SPAWN_EGG, COW_SPAWN_EGG, CREEPER_SPAWN_EGG, DOLPHIN_SPAWN_EGG, DONKEY_SPAWN_EGG, DROWNED_SPAWN_EGG, ELDER_GUARDIAN_SPAWN_EGG, ENDER_DRAGON_SPAWN_EGG, ENDERMAN_SPAWN_EGG, ENDERMITE_SPAWN_EGG, EVOKER_SPAWN_EGG, FOX_SPAWN_EGG, FROG_SPAWN_EGG, GHAST_SPAWN_EGG, GLOW_SQUID_SPAWN_EGG, GOAT_SPAWN_EGG, GUARDIAN_SPAWN_EGG, HOGLIN_SPAWN_EGG, HORSE_SPAWN_EGG, HUSK_SPAWN_EGG, IRON_GOLEM_SPAWN_EGG, LLAMA_SPAWN_EGG, MAGMA_CUBE_SPAWN_EGG, MOOSHROOM_SPAWN_EGG, MULE_SPAWN_EGG, OCELOT_SPAWN_EGG, PANDA_SPAWN_EGG, PARROT_SPAWN_EGG, PHANTOM_SPAWN_EGG, PIG_SPAWN_EGG, PIGLIN_SPAWN_EGG, PIGLIN_BRUTE_SPAWN_EGG, PILLAGER_SPAWN_EGG, POLAR_BEAR_SPAWN_EGG, PUFFERFISH_SPAWN_EGG, RABBIT_SPAWN_EGG, RAVAGER_SPAWN_EGG, SALMON_SPAWN_EGG, SHEEP_SPAWN_EGG, SHULKER_SPAWN_EGG, SILVERFISH_SPAWN_EGG, SKELETON_SPAWN_EGG, SKELETON_HORSE_SPAWN_EGG, SLIME_SPAWN_EGG, SNIFFER_SPAWN_EGG, SNOW_GOLEM_SPAWN_EGG, SPIDER_SPAWN_EGG, SQUID_SPAWN_EGG, STRAY_SPAWN_EGG, STRIDER_SPAWN_EGG, TADPOLE_SPAWN_EGG, TRADER_LLAMA_SPAWN_EGG, TROPICAL_FISH_SPAWN_EGG, TURTLE_SPAWN_EGG, VEX_SPAWN_EGG, VILLAGER_SPAWN_EGG, VINDICATOR_SPAWN_EGG, WANDERING_TRADER_SPAWN_EGG, WARDEN_SPAWN_EGG, WITCH_SPAWN_EGG, WITHER_SPAWN_EGG, WITHER_SKELETON_SPAWN_EGG, WOLF_SPAWN_EGG, ZOGLIN_SPAWN_EGG, ZOMBIE_SPAWN_EGG, ZOMBIE_HORSE_SPAWN_EGG, ZOMBIE_VILLAGER_SPAWN_EGG, ZOMBIFIED_PIGLIN_SPAWN_EGG ->
                    List.of(SortType.SPAWNER_SPAWN_EGG);
            case LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS, CHAINMAIL_HELMET, CHAINMAIL_CHESTPLATE, CHAINMAIL_LEGGINGS, CHAINMAIL_BOOTS, IRON_HELMET, IRON_CHESTPLATE, IRON_LEGGINGS, IRON_BOOTS, DIAMOND_HELMET, DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, GOLDEN_HELMET, GOLDEN_CHESTPLATE, GOLDEN_LEGGINGS, GOLDEN_BOOTS, NETHERITE_HELMET, NETHERITE_CHESTPLATE, NETHERITE_LEGGINGS, NETHERITE_BOOTS ->
                    List.of(SortType.ARMORS);
            case WOODEN_SWORD, WOODEN_SHOVEL, WOODEN_PICKAXE, WOODEN_AXE, WOODEN_HOE, STONE_SWORD, STONE_SHOVEL, STONE_PICKAXE, STONE_AXE, STONE_HOE, GOLDEN_SWORD, GOLDEN_SHOVEL, GOLDEN_PICKAXE, GOLDEN_AXE, GOLDEN_HOE, IRON_SWORD, IRON_SHOVEL, IRON_PICKAXE, IRON_AXE, IRON_HOE, DIAMOND_SWORD, DIAMOND_SHOVEL, DIAMOND_PICKAXE, DIAMOND_AXE, DIAMOND_HOE, NETHERITE_SWORD, NETHERITE_SHOVEL, NETHERITE_PICKAXE, NETHERITE_AXE, NETHERITE_HOE, SHEARS, SHIELD, TOTEM_OF_UNDYING, BRUSH, TRIDENT, CROSSBOW ->
                    List.of(SortType.TOOL);
            case STRING, FEATHER, GUNPOWDER, INK_SAC, GLOW_INK_SAC, BONE, ROTTEN_FLESH, ENDER_PEARL, BLAZE_ROD, GHAST_TEAR, SPIDER_EYE, FERMENTED_SPIDER_EYE, BLAZE_POWDER, MAGMA_CREAM, ENDER_EYE, SKELETON_SKULL, WITHER_SKELETON_SKULL, ZOMBIE_HEAD, CREEPER_HEAD, DRAGON_HEAD, PIGLIN_HEAD, PHANTOM_MEMBRANE, NAUTILUS_SHELL ->
                    List.of(SortType.MOB_LOOT);
            case PORKCHOP, BEEF, CHICKEN, COD, SALMON, TROPICAL_FISH, PUFFERFISH, EGG, RABBIT_FOOT, RABBIT_HIDE, MUTTON ->
                    List.of(SortType.PASSIVE_LOOT);
            case COOKED_RABBIT, COOKED_BEEF, COOKED_PORKCHOP, COOKED_CHICKEN, COOKED_COD, COOKED_SALMON, COOKED_MUTTON ->
                    List.of(SortType.PASSIVE_LOOT, SortType.FOOD);
            case GOLDEN_APPLE, ENCHANTED_GOLDEN_APPLE, DRIED_KELP, SUGAR, CAKE, BAKED_POTATO, GOLDEN_CARROT, PUMPKIN_PIE, RABBIT_STEW, RABBIT, BEETROOT_SOUP, SUSPICIOUS_STEW ->
                    List.of(SortType.FOOD);
            case POTION, GLASS_BOTTLE, SPLASH_POTION, LINGERING_POTION, BREWING_STAND, TIPPED_ARROW ->
                    List.of(SortType.POTION);
            case ENCHANTED_BOOK -> List.of(SortType.ENCHANTED_BOOK);
            default -> List.of(SortType.MISC);
        };
    }
    public enum SortType{
        ENCHANTED_BOOK,
        ARMORS,
        TOOL,
        BLOCK,
        POTION,
        REDSTONE,
        SPAWNER_SPAWN_EGG,
        WOOD,
        NETHER,
        NATURAL_BLOCK,
        MOB_LOOT,
        MINERAI,
        CROP,
        PASSIVE_LOOT,
        FOOD,
        MISC
    }
}